version: '3.8'

services:
  postgres:
    image: postgres:latest  # Última versión disponible
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin  # Cambia esto en producción
      POSTGRES_DB: final
    ports:
      - "5432:5432"
    volumes:
      - ./init-scripts:/docker-entrypoint-initdb.d
      - postgres_data:/var/lib/postgresql/data
      # Scripts SQL para inicializar la DB

  springboot:
    build:
      context: ./demo
      dockerfile: Dockerfile
    container_name: sping-container
    ports:
      - "8080:8080"
    restart: always
    environment:
      DB_HOST: postgres
      DB_USERNAME: admin
      DB_PASSWORD: admin

volumes:
  postgres_data:
    driver: local
